config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :users

  root 'welcome#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    members_path
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :father_name, :date_of_birth, :pan_no, :address, :nominee_name, :nominee_relationship, :nominee_date_of_birth, :rbi_cc_op_no, :rbi_ncop_no, :business_enrolment_date, :bank_name, :bank_account_no, :branch_name, :ifsc_code, :mobile_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatNamakkal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth, :start_year=>1950 %>
  </div>
  <div class="field">
    <%= f.label :pan_no %><br>
    <%= f.text_field :pan_no %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :nominee_name %><br>
    <%= f.text_field :nominee_name %>
  </div>
  <div class="field">
    <%= f.label :nominee_relationship %><br>
    <%= f.text_field :nominee_relationship %>
  </div>
  <div class="field">
    <%= f.label :nominee_date_of_birth %><br>
    <%= f.date_select :nominee_date_of_birth, :start_year=>1950 %>
  </div>
  <div class="field">
    <%= f.label :rbi_cc_op_no %><br>
    <%= f.text_field :rbi_cc_op_no %>
  </div>
  <div class="field">
    <%= f.label :rbi_ncop_no %><br>
    <%= f.text_field :rbi_ncop_no %>
  </div>
  <div class="field">
    <%= f.label :business_enrolment_date %><br>
    <%= f.date_select :business_enrolment_date, :start_year=>1950 %>
  </div>
  <div class="field">
    <%= f.label :bank_name %><br>
    <%= f.text_field :bank_name %>
  </div>
  <div class="field">
    <%= f.label :bank_account_no %><br>
    <%= f.text_field :bank_account_no %>
  </div>
  <div class="field">
    <%= f.label :branch_name %><br>
    <%= f.text_field :branch_name %>
  </div>
  <div class="field">
    <%= f.label :ifsc_code %><br>
    <%= f.text_field :ifsc_code %>
  </div>
  <div class="field">
    <%= f.label :mobile_no %><br>
    <%= f.text_field :mobile_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Father name</th>
      <th>Date of birth</th>
      <th>Pan no</th>
      <th>Address</th>
      <th>Nominee name</th>
      <th>Nominee relationship</th>
      <th>Nominee date of birth</th>
      <th>Rbi cc op no</th>
      <th>Rbi ncop no</th>
      <th>Business enrolment date</th>
      <th>Bank name</th>
      <th>Bank account no</th>
      <th>Branch name</th>
      <th>Ifsc code</th>
      <th>Mobile no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.father_name %></td>
        <td><%= member.date_of_birth %></td>
        <td><%= member.pan_no %></td>
        <td><%= member.address %></td>
        <td><%= member.nominee_name %></td>
        <td><%= member.nominee_relationship %></td>
        <td><%= member.nominee_date_of_birth %></td>
        <td><%= member.rbi_cc_op_no %></td>
        <td><%= member.rbi_ncop_no %></td>
        <td><%= member.business_enrolment_date %></td>
        <td><%= member.bank_name %></td>
        <td><%= member.bank_account_no %></td>
        <td><%= member.branch_name %></td>
        <td><%= member.ifsc_code %></td>
        <td><%= member.mobile_no %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @member.father_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @member.date_of_birth %>
</p>

<p>
  <strong>Pan no:</strong>
  <%= @member.pan_no %>
</p>

<p>
  <strong>Address:</strong>
  <%= @member.address %>
</p>

<p>
  <strong>Nominee name:</strong>
  <%= @member.nominee_name %>
</p>

<p>
  <strong>Nominee relationship:</strong>
  <%= @member.nominee_relationship %>
</p>

<p>
  <strong>Nominee date of birth:</strong>
  <%= @member.nominee_date_of_birth %>
</p>

<p>
  <strong>Rbi cc op no:</strong>
  <%= @member.rbi_cc_op_no %>
</p>

<p>
  <strong>Rbi ncop no:</strong>
  <%= @member.rbi_ncop_no %>
</p>

<p>
  <strong>Business enrolment date:</strong>
  <%= @member.business_enrolment_date %>
</p>

<p>
  <strong>Bank name:</strong>
  <%= @member.bank_name %>
</p>

<p>
  <strong>Bank account no:</strong>
  <%= @member.bank_account_no %>
</p>

<p>
  <strong>Branch name:</strong>
  <%= @member.branch_name %>
</p>

<p>
  <strong>Ifsc code:</strong>
  <%= @member.ifsc_code %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @member.mobile_no %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>